name: grimoire
description: wiki apps based on git repositories

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.6+1

environment:
  flutter: ">=3.7.0"
  sdk: ">=2.18.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  json_annotation: ^4.8.0
  go_router: ^6.0.1
  equatable: ^2.0.5
  retrofit: '>=4.0.0 <5.0.0'
  get_it: ^7.2.0
  get: ^4.6.5
  flutter_riverpod: ^2.3.0
  dio: ^5.0.1
  injectable: ^2.1.0
  package_info_plus: ^3.0.3
  font_awesome_flutter: ^10.3.0
  markdown: ^6.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^7.0.1
  flutter_highlighter: ^0.1.1
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.5
  google_fonts: ^3.0.1
  lottie: ^2.2.0
  typesense: ^0.3.0
  scroll_to_index: ^3.0.1
  oauth2: ^2.0.0
  envied: ^0.3.0
  intl: ^0.17.0
  url_launcher: ^6.1.8
  shimmer: ^2.0.0
  crypto: 3.0.2
  dropdown_search: ^5.0.6
  bubble_tab_indicator: ^0.1.6
  chucker_flutter: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  retrofit_generator: '>=5.0.0 <6.0.0'
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.0
  hive_generator: ^2.0.0
  envied_generator: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - packages/grimoire/assets/lottie/loading_animation_bored_hand.json
    - packages/grimoire/assets/icons/grimoire_logo_bw.png
    - packages/grimoire/assets/icons/typesense_logo.svg
    - packages/grimoire/assets/images/grimoire_bg.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SegoeUI
      fonts:
        - asset: fonts/seguiemj.ttf
        - asset: fonts/segoeuib.ttf
          weight: 700
        - asset: fonts/segoeuii.ttf
          style: italic
        - asset: fonts/seguisym.ttf
        - asset: fonts/seguisb.ttf
          weight: 300
        - asset: fonts/seguisbi.ttf
          weight: 300
          style: italic
    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
        - asset: fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: fonts/JetBrainsMono-Italic.ttf
          style: italic
        - asset: fonts/JetBrainsMono-SemiBold.ttf
          weight: 300
        - asset: fonts/JetBrainsMono-SemiBoldItalic.ttf
          weight: 300
          style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
